head: 
   favicon: "https://ooo.0o0.ooo/2017/05/27/59294212bc16e.png" #  the favicon
   high_res_favicon: "https://ooo.0o0.ooo/2017/06/08/5939484dc618e.png" #  the favicon using high quality format
   apple_touch_icon: "https://ooo.0o0.ooo/2017/06/08/5939484dc618e.png" # the iOS Home button icon
   keywords: "Hide and Seek" #  the site keywords

uiux:
   android_chrome_color: "#eeeeee" #  the color of the Chrome address bar
   nprogress_color: "#29d" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: true

background: 
   purecolor: "#eeeeee" # the background color

img: 
   avatar: "https://ooo.0o0.ooo/2017/06/17/5944a14d74d37.png" # your avatar


card: 
   card_shadow: 1 # card shadow (0-24), 0 is not displayed
   card_hoverable: false # When the hover to deepen the shadow

+many_authors: false


sns_share: # SNS Share Switch
   twitter: true
   facebook: false
   googleplus: false
   weibo: true
   linkedin: false
   qq: true
   telegram: true

disqus:
   disqus_shortname: "m0dulo" # Your disqus 
   disqus_button: false # disqus load button
   disqus_proxy: false # # disqus proxy(Do not use)
   disqus_proxy_url: "" # (Do not use)
   disqus_api_key: "" # (Do not use)

google_analytics: ""  # google analytics code

lang: "zh-CN"  # lang

deploy: "coding" # if you used coding pages